spring:
  datasource:
#    url: jdbc:h2:file:./data/file_processing
    url: jdbc:h2:mem:file_processing
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

#    defer-datasource-initialization: true
