spring:
  datasource:
    #url: jdbc:h2:file:./file_processing
    url: jdbc:h2:mem:file_processing
    #url: jdbc:h2:tcp://localhost/~/file_processing
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  ipApiBaseUrl: http://ip-api.com

local:
  server:
    port: 9000





#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
